### ISSUE TITLE
Issue with rating filter scroll on Listify 2.0.2

### ISSUE THREAD

**Issue by vladpekh** [Astoundify/listify-child#1]
Found one small issue with rating select not scrolling back to comments (short screencast): 

![ratingscroll](https://user-images.githubusercontent.com/1377208/27622218-b68ace12-5ba3-11e7-9c59-fc18b48a56cb.gif)

Please delete this issue if this is not the right place to report it.
Thanks

**Comment by spencerfinnell** [comment]
Thank you. I have fixed this in the main theme.
