### ISSUE TITLE
Page: Recent Listings widget -> Display error

### ISSUE THREAD

**Issue by DeLocatiegids** [Astoundify/listify-child#2]
Hello

on listify 2.0.3 when i use the recent listing widget on front page the result is not good.
When i use multiple of this plugin (with different options) then al the widget use the same option.

The first widget shows 15 listings, all not featured. The settings are 6 featured listings.
The second widget shows 15 listings and the settings are 15 so thats right.

When i added a 3th one for testing with featured listing only then al 3 widget show the listing like the third settings.

kind regards

**Comment by spencerfinnell** [comment]
Please open a ticket https://astoundify.com/account/

**Comment by DeLocatiegids** [comment]
I can't use support because my support license is expired. Im in the 
listify beta group on fb, posted the problem there. Adam Pickering asked 
me to contact a developer but the problem is that i can't. If i can't 
report the bugs then im wasting my time with testing...


Kind regards

Spencer Finnell schreef op 2017-06-30 00:02:
