### ISSUE TITLE
Shortcode for custom recent listings widget not working as it should 

### ISSUE THREAD

**Issue by DeLocatiegids** [Astoundify/listify-child#3]
When i use the shortcode: [jobs per_page="15" show_filters="false" orderby="rand"]. the layout i broken.
This occurs when i use it in a textwidget on frontpage and when i use it on a new page.

Example:

https://delocatiegids.nl/test

**Comment by spencerfinnell** [comment]
Please open a ticket https://astoundify.com/account/
